# Generated by Django 4.0.2 on 2022-09-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_liveequityresult_change_perc'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquityThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
            ],
        ),
    ]
